import { Suspense } from 'react';

import Footer from './Footer';
import './globals.css';
import Header from './Header';
import Loading from './loading';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="container mx-auto bg-slate-700 text-slate-50">
        <Header />
        <Suspense fallback={<Loading />}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  );
}
